version: "3.9"

services:
  backend:
    container_name: backend
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    working_dir: /app
    restart: on-failure
    env_file:
      - .env

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - .:/docker-entrypoint-initdb.d
    restart: on-failure

